name = "Mosek"
uuid = "6405355b-0ac2-5fba-af84-adbd65488c0e"
repo = "https://github.com/JuliaOpt/Mosek.jl.git"
version = "0.9.9"

[deps]
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"

[compat]
julia = "0.7, 1"
MathProgBase = "0.7.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
